name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 🔑 This is missing!

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: ChristinRaju
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      - name: Create output directory
        run: mkdir -p output

      - name: Move generated files
        run: mv snake*.svg output/

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generated Snake animation"
          add: "output/*"
